// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKtWBjtANeNmIDS2xy89T-Lk2xZQbCbbI',
    appId: '1:482963155468:web:a85c43147270cdc001dc29',
    messagingSenderId: '482963155468',
    projectId: 'tactix-academy-e9b38',
    authDomain: 'tactix-academy-e9b38.firebaseapp.com',
    storageBucket: 'tactix-academy-e9b38.firebasestorage.app',
    measurementId: 'G-X839TXCKVB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQarY9Tc7bn25s8mLH8Fpjm57vUi6ukKo',
    appId: '1:482963155468:android:84e6211914d9c7d101dc29',
    messagingSenderId: '482963155468',
    projectId: 'tactix-academy-e9b38',
    storageBucket: 'tactix-academy-e9b38.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDss8qgOXND_C9ucaWF2w3iAsN3jDWmr80',
    appId: '1:482963155468:ios:ad79716869419ff501dc29',
    messagingSenderId: '482963155468',
    projectId: 'tactix-academy-e9b38',
    storageBucket: 'tactix-academy-e9b38.firebasestorage.app',
    iosBundleId: 'com.tactixacademy.manager',
  );

}